In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/Social_Network_Ads.csv',
               usecols=['Age','EstimatedSalary','Purchased'])

In [4]:
df.head(2)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [5]:
x=df.drop(columns='Purchased')
y=df['Purchased']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=22)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc=StandardScaler()

In [10]:
x_train_new=sc.fit_transform(x_train)

In [11]:
x_test_new=sc.transform(x_test)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()

In [13]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [14]:
y_pred=classifier.predict(x_test_new)

In [15]:
y_pred

array([1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
cn=confusion_matrix(y_test,y_pred)

In [18]:
cn

array([[47,  4],
       [ 6, 23]])

In [19]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(y_test,y_pred)

0.875

In [48]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')

In [49]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [50]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [51]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
lb=LabelEncoder()

In [54]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [55]:
x=df.drop(columns='has_covid')
y=df['has_covid']

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=22)

In [57]:
x_train_new=sc.fit_transform(x_train)

In [58]:
x_test_new=sc.transform(x_test)

In [59]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [60]:
y_pred=classifier.predict(x_test_new)

In [61]:
cn=confusion_matrix(y_test,y_pred)

In [62]:
accuracy_score(y_test,y_pred)

0.55

In [65]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv',
               usecols=['age','fever','has_covid'])

In [66]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [67]:
x=df.drop(columns='has_covid')
y=df['has_covid']

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=22)

In [69]:
x_train_new=sc.fit_transform(x_train)

In [70]:
x_test_new=sc.transform(x_test)

In [71]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [72]:
y_pred=classifier.predict(x_test_new)

In [73]:
confusion_matrix(y_test,y_pred)

array([[7, 2],
       [8, 3]])

In [74]:
accuracy_score(y_test,y_pred)

0.5