In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/insurance - insurance.csv')

In [4]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [6]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
x=df.drop(columns='charges')
y=df['charges']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                               test_size=0.2,
                                               random_state=21)

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
rf=RandomForestRegressor()

In [17]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [18]:
y_pred=rf.predict(x_test)

In [19]:
from sklearn.metrics import r2_score

In [20]:
r2_score(y_test,y_pred)

0.8137850112694482

In [21]:
model=RandomForestRegressor(
    n_estimators=100,
    max_features='sqrt',
    max_depth=10,
    max_leaf_nodes=10
)

In [22]:
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, max_features='sqrt', max_leaf_nodes=10)

In [23]:
y_pred=model.predict(x_test)

In [24]:
r2_score(y_test,y_pred)

0.7681007642523765